apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: MONGO_URL

            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: KAFKA_BROKER

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: JWT_SECRET